# Generated by Django 4.1.5 on 2023-02-22 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.TextField(blank=True),
        ),
    ]
